/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppDiscoverImport } from './routes/_app/discover'
import { Route as publicHealthcheckImport } from './routes/(public)/healthcheck'
import { Route as AppProfileRouteImport } from './routes/_app/profile/route'
import { Route as AppFriendsRouteImport } from './routes/_app/friends/route'
import { Route as AppChatRouteImport } from './routes/_app/chat/route'
import { Route as publicAuthRouteImport } from './routes/(public)/auth/route'
import { Route as AppProfileIndexImport } from './routes/_app/profile/index'
import { Route as AppFriendsIndexImport } from './routes/_app/friends/index'
import { Route as AppChatIndexImport } from './routes/_app/chat/index'
import { Route as AppTestNotificationsImport } from './routes/_app/test/notifications'
import { Route as AppProfileSettingsImport } from './routes/_app/profile/settings'
import { Route as AppProfileAppearenceImport } from './routes/_app/profile/appearence'
import { Route as AppFriendsRequestsImport } from './routes/_app/friends/requests'
import { Route as AppFriendsAddImport } from './routes/_app/friends/add'
import { Route as AppChatSplatImport } from './routes/_app/chat/$'
import { Route as publicAuthVerifyAccountImport } from './routes/(public)/auth/verify-account'
import { Route as publicAuthSignUpImport } from './routes/(public)/auth/sign-up'
import { Route as publicAuthSignInImport } from './routes/(public)/auth/sign-in'
import { Route as publicAuthForgetPasswordImport } from './routes/(public)/auth/forget-password'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppDiscoverRoute = AppDiscoverImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)

const publicHealthcheckRoute = publicHealthcheckImport.update({
  id: '/(public)/healthcheck',
  path: '/healthcheck',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileRouteRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)

const AppFriendsRouteRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)

const AppChatRouteRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)

const publicAuthRouteRoute = publicAuthRouteImport.update({
  id: '/(public)/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRouteRoute,
} as any)

const AppFriendsIndexRoute = AppFriendsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFriendsRouteRoute,
} as any)

const AppChatIndexRoute = AppChatIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRouteRoute,
} as any)

const AppTestNotificationsRoute = AppTestNotificationsImport.update({
  id: '/test/notifications',
  path: '/test/notifications',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileSettingsRoute = AppProfileSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProfileRouteRoute,
} as any)

const AppProfileAppearenceRoute = AppProfileAppearenceImport.update({
  id: '/appearence',
  path: '/appearence',
  getParentRoute: () => AppProfileRouteRoute,
} as any)

const AppFriendsRequestsRoute = AppFriendsRequestsImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppFriendsRouteRoute,
} as any)

const AppFriendsAddRoute = AppFriendsAddImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppFriendsRouteRoute,
} as any)

const AppChatSplatRoute = AppChatSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppChatRouteRoute,
} as any)

const publicAuthVerifyAccountRoute = publicAuthVerifyAccountImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => publicAuthRouteRoute,
} as any)

const publicAuthSignUpRoute = publicAuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicAuthRouteRoute,
} as any)

const publicAuthSignInRoute = publicAuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicAuthRouteRoute,
} as any)

const publicAuthForgetPasswordRoute = publicAuthForgetPasswordImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => publicAuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/(public)/auth': {
      id: '/(public)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof publicAuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppImport
    }
    '/(public)/healthcheck': {
      id: '/(public)/healthcheck'
      path: '/healthcheck'
      fullPath: '/healthcheck'
      preLoaderRoute: typeof publicHealthcheckImport
      parentRoute: typeof rootRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverImport
      parentRoute: typeof AppImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/(public)/auth/forget-password': {
      id: '/(public)/auth/forget-password'
      path: '/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof publicAuthForgetPasswordImport
      parentRoute: typeof publicAuthRouteImport
    }
    '/(public)/auth/sign-in': {
      id: '/(public)/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof publicAuthSignInImport
      parentRoute: typeof publicAuthRouteImport
    }
    '/(public)/auth/sign-up': {
      id: '/(public)/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof publicAuthSignUpImport
      parentRoute: typeof publicAuthRouteImport
    }
    '/(public)/auth/verify-account': {
      id: '/(public)/auth/verify-account'
      path: '/verify-account'
      fullPath: '/auth/verify-account'
      preLoaderRoute: typeof publicAuthVerifyAccountImport
      parentRoute: typeof publicAuthRouteImport
    }
    '/_app/chat/$': {
      id: '/_app/chat/$'
      path: '/$'
      fullPath: '/chat/$'
      preLoaderRoute: typeof AppChatSplatImport
      parentRoute: typeof AppChatRouteImport
    }
    '/_app/friends/add': {
      id: '/_app/friends/add'
      path: '/add'
      fullPath: '/friends/add'
      preLoaderRoute: typeof AppFriendsAddImport
      parentRoute: typeof AppFriendsRouteImport
    }
    '/_app/friends/requests': {
      id: '/_app/friends/requests'
      path: '/requests'
      fullPath: '/friends/requests'
      preLoaderRoute: typeof AppFriendsRequestsImport
      parentRoute: typeof AppFriendsRouteImport
    }
    '/_app/profile/appearence': {
      id: '/_app/profile/appearence'
      path: '/appearence'
      fullPath: '/profile/appearence'
      preLoaderRoute: typeof AppProfileAppearenceImport
      parentRoute: typeof AppProfileRouteImport
    }
    '/_app/profile/settings': {
      id: '/_app/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AppProfileSettingsImport
      parentRoute: typeof AppProfileRouteImport
    }
    '/_app/test/notifications': {
      id: '/_app/test/notifications'
      path: '/test/notifications'
      fullPath: '/test/notifications'
      preLoaderRoute: typeof AppTestNotificationsImport
      parentRoute: typeof AppImport
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexImport
      parentRoute: typeof AppChatRouteImport
    }
    '/_app/friends/': {
      id: '/_app/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof AppFriendsIndexImport
      parentRoute: typeof AppFriendsRouteImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppProfileRouteImport
    }
  }
}

// Create and export the route tree

interface AppChatRouteRouteChildren {
  AppChatSplatRoute: typeof AppChatSplatRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteRouteChildren: AppChatRouteRouteChildren = {
  AppChatSplatRoute: AppChatSplatRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteRouteWithChildren = AppChatRouteRoute._addFileChildren(
  AppChatRouteRouteChildren,
)

interface AppFriendsRouteRouteChildren {
  AppFriendsAddRoute: typeof AppFriendsAddRoute
  AppFriendsRequestsRoute: typeof AppFriendsRequestsRoute
  AppFriendsIndexRoute: typeof AppFriendsIndexRoute
}

const AppFriendsRouteRouteChildren: AppFriendsRouteRouteChildren = {
  AppFriendsAddRoute: AppFriendsAddRoute,
  AppFriendsRequestsRoute: AppFriendsRequestsRoute,
  AppFriendsIndexRoute: AppFriendsIndexRoute,
}

const AppFriendsRouteRouteWithChildren = AppFriendsRouteRoute._addFileChildren(
  AppFriendsRouteRouteChildren,
)

interface AppProfileRouteRouteChildren {
  AppProfileAppearenceRoute: typeof AppProfileAppearenceRoute
  AppProfileSettingsRoute: typeof AppProfileSettingsRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteRouteChildren: AppProfileRouteRouteChildren = {
  AppProfileAppearenceRoute: AppProfileAppearenceRoute,
  AppProfileSettingsRoute: AppProfileSettingsRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteRouteWithChildren = AppProfileRouteRoute._addFileChildren(
  AppProfileRouteRouteChildren,
)

interface AppRouteChildren {
  AppChatRouteRoute: typeof AppChatRouteRouteWithChildren
  AppFriendsRouteRoute: typeof AppFriendsRouteRouteWithChildren
  AppProfileRouteRoute: typeof AppProfileRouteRouteWithChildren
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTestNotificationsRoute: typeof AppTestNotificationsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRouteRoute: AppChatRouteRouteWithChildren,
  AppFriendsRouteRoute: AppFriendsRouteRouteWithChildren,
  AppProfileRouteRoute: AppProfileRouteRouteWithChildren,
  AppDiscoverRoute: AppDiscoverRoute,
  AppHomeRoute: AppHomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppTestNotificationsRoute: AppTestNotificationsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface publicAuthRouteRouteChildren {
  publicAuthForgetPasswordRoute: typeof publicAuthForgetPasswordRoute
  publicAuthSignInRoute: typeof publicAuthSignInRoute
  publicAuthSignUpRoute: typeof publicAuthSignUpRoute
  publicAuthVerifyAccountRoute: typeof publicAuthVerifyAccountRoute
}

const publicAuthRouteRouteChildren: publicAuthRouteRouteChildren = {
  publicAuthForgetPasswordRoute: publicAuthForgetPasswordRoute,
  publicAuthSignInRoute: publicAuthSignInRoute,
  publicAuthSignUpRoute: publicAuthSignUpRoute,
  publicAuthVerifyAccountRoute: publicAuthVerifyAccountRoute,
}

const publicAuthRouteRouteWithChildren = publicAuthRouteRoute._addFileChildren(
  publicAuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/auth': typeof publicAuthRouteRouteWithChildren
  '/chat': typeof AppChatRouteRouteWithChildren
  '/friends': typeof AppFriendsRouteRouteWithChildren
  '/profile': typeof AppProfileRouteRouteWithChildren
  '/healthcheck': typeof publicHealthcheckRoute
  '/discover': typeof AppDiscoverRoute
  '/home': typeof AppHomeRoute
  '/': typeof AppIndexRoute
  '/auth/forget-password': typeof publicAuthForgetPasswordRoute
  '/auth/sign-in': typeof publicAuthSignInRoute
  '/auth/sign-up': typeof publicAuthSignUpRoute
  '/auth/verify-account': typeof publicAuthVerifyAccountRoute
  '/chat/$': typeof AppChatSplatRoute
  '/friends/add': typeof AppFriendsAddRoute
  '/friends/requests': typeof AppFriendsRequestsRoute
  '/profile/appearence': typeof AppProfileAppearenceRoute
  '/profile/settings': typeof AppProfileSettingsRoute
  '/test/notifications': typeof AppTestNotificationsRoute
  '/chat/': typeof AppChatIndexRoute
  '/friends/': typeof AppFriendsIndexRoute
  '/profile/': typeof AppProfileIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof publicAuthRouteRouteWithChildren
  '/healthcheck': typeof publicHealthcheckRoute
  '/discover': typeof AppDiscoverRoute
  '/home': typeof AppHomeRoute
  '/': typeof AppIndexRoute
  '/auth/forget-password': typeof publicAuthForgetPasswordRoute
  '/auth/sign-in': typeof publicAuthSignInRoute
  '/auth/sign-up': typeof publicAuthSignUpRoute
  '/auth/verify-account': typeof publicAuthVerifyAccountRoute
  '/chat/$': typeof AppChatSplatRoute
  '/friends/add': typeof AppFriendsAddRoute
  '/friends/requests': typeof AppFriendsRequestsRoute
  '/profile/appearence': typeof AppProfileAppearenceRoute
  '/profile/settings': typeof AppProfileSettingsRoute
  '/test/notifications': typeof AppTestNotificationsRoute
  '/chat': typeof AppChatIndexRoute
  '/friends': typeof AppFriendsIndexRoute
  '/profile': typeof AppProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/(public)/auth': typeof publicAuthRouteRouteWithChildren
  '/_app/chat': typeof AppChatRouteRouteWithChildren
  '/_app/friends': typeof AppFriendsRouteRouteWithChildren
  '/_app/profile': typeof AppProfileRouteRouteWithChildren
  '/(public)/healthcheck': typeof publicHealthcheckRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/': typeof AppIndexRoute
  '/(public)/auth/forget-password': typeof publicAuthForgetPasswordRoute
  '/(public)/auth/sign-in': typeof publicAuthSignInRoute
  '/(public)/auth/sign-up': typeof publicAuthSignUpRoute
  '/(public)/auth/verify-account': typeof publicAuthVerifyAccountRoute
  '/_app/chat/$': typeof AppChatSplatRoute
  '/_app/friends/add': typeof AppFriendsAddRoute
  '/_app/friends/requests': typeof AppFriendsRequestsRoute
  '/_app/profile/appearence': typeof AppProfileAppearenceRoute
  '/_app/profile/settings': typeof AppProfileSettingsRoute
  '/_app/test/notifications': typeof AppTestNotificationsRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/friends/': typeof AppFriendsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/chat'
    | '/friends'
    | '/profile'
    | '/healthcheck'
    | '/discover'
    | '/home'
    | '/'
    | '/auth/forget-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-account'
    | '/chat/$'
    | '/friends/add'
    | '/friends/requests'
    | '/profile/appearence'
    | '/profile/settings'
    | '/test/notifications'
    | '/chat/'
    | '/friends/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/healthcheck'
    | '/discover'
    | '/home'
    | '/'
    | '/auth/forget-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-account'
    | '/chat/$'
    | '/friends/add'
    | '/friends/requests'
    | '/profile/appearence'
    | '/profile/settings'
    | '/test/notifications'
    | '/chat'
    | '/friends'
    | '/profile'
  id:
    | '__root__'
    | '/_app'
    | '/(public)/auth'
    | '/_app/chat'
    | '/_app/friends'
    | '/_app/profile'
    | '/(public)/healthcheck'
    | '/_app/discover'
    | '/_app/home'
    | '/_app/'
    | '/(public)/auth/forget-password'
    | '/(public)/auth/sign-in'
    | '/(public)/auth/sign-up'
    | '/(public)/auth/verify-account'
    | '/_app/chat/$'
    | '/_app/friends/add'
    | '/_app/friends/requests'
    | '/_app/profile/appearence'
    | '/_app/profile/settings'
    | '/_app/test/notifications'
    | '/_app/chat/'
    | '/_app/friends/'
    | '/_app/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  publicAuthRouteRoute: typeof publicAuthRouteRouteWithChildren
  publicHealthcheckRoute: typeof publicHealthcheckRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  publicAuthRouteRoute: publicAuthRouteRouteWithChildren,
  publicHealthcheckRoute: publicHealthcheckRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/(public)/auth",
        "/(public)/healthcheck"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/chat",
        "/_app/friends",
        "/_app/profile",
        "/_app/discover",
        "/_app/home",
        "/_app/",
        "/_app/test/notifications"
      ]
    },
    "/(public)/auth": {
      "filePath": "(public)/auth/route.tsx",
      "children": [
        "/(public)/auth/forget-password",
        "/(public)/auth/sign-in",
        "/(public)/auth/sign-up",
        "/(public)/auth/verify-account"
      ]
    },
    "/_app/chat": {
      "filePath": "_app/chat/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/chat/$",
        "/_app/chat/"
      ]
    },
    "/_app/friends": {
      "filePath": "_app/friends/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/friends/add",
        "/_app/friends/requests",
        "/_app/friends/"
      ]
    },
    "/_app/profile": {
      "filePath": "_app/profile/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/profile/appearence",
        "/_app/profile/settings",
        "/_app/profile/"
      ]
    },
    "/(public)/healthcheck": {
      "filePath": "(public)/healthcheck.tsx"
    },
    "/_app/discover": {
      "filePath": "_app/discover.tsx",
      "parent": "/_app"
    },
    "/_app/home": {
      "filePath": "_app/home.tsx",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/(public)/auth/forget-password": {
      "filePath": "(public)/auth/forget-password.tsx",
      "parent": "/(public)/auth"
    },
    "/(public)/auth/sign-in": {
      "filePath": "(public)/auth/sign-in.tsx",
      "parent": "/(public)/auth"
    },
    "/(public)/auth/sign-up": {
      "filePath": "(public)/auth/sign-up.tsx",
      "parent": "/(public)/auth"
    },
    "/(public)/auth/verify-account": {
      "filePath": "(public)/auth/verify-account.tsx",
      "parent": "/(public)/auth"
    },
    "/_app/chat/$": {
      "filePath": "_app/chat/$.tsx",
      "parent": "/_app/chat"
    },
    "/_app/friends/add": {
      "filePath": "_app/friends/add.tsx",
      "parent": "/_app/friends"
    },
    "/_app/friends/requests": {
      "filePath": "_app/friends/requests.tsx",
      "parent": "/_app/friends"
    },
    "/_app/profile/appearence": {
      "filePath": "_app/profile/appearence.tsx",
      "parent": "/_app/profile"
    },
    "/_app/profile/settings": {
      "filePath": "_app/profile/settings.tsx",
      "parent": "/_app/profile"
    },
    "/_app/test/notifications": {
      "filePath": "_app/test/notifications.tsx",
      "parent": "/_app"
    },
    "/_app/chat/": {
      "filePath": "_app/chat/index.tsx",
      "parent": "/_app/chat"
    },
    "/_app/friends/": {
      "filePath": "_app/friends/index.tsx",
      "parent": "/_app/friends"
    },
    "/_app/profile/": {
      "filePath": "_app/profile/index.tsx",
      "parent": "/_app/profile"
    }
  }
}
ROUTE_MANIFEST_END */
