const Pages = () => {
  return (
    <div className="text-foreground">
     Lectus lectus duis consectetur imperdiet sed turpis feugiat. Dis malesuada sit lacus. Nullam suscipit sed faucibus, dolor volutpat condimentum in consectetur posuere habitasse dignissim malesuada. Purus praesent nunc nam metus enim convallis, vivamus rhoncus et ex sed consectetur luctus sed cursus ac tincidunt fermentum, suspendisse eget tortor vitae magnis vitae in. Tincidunt congue nec magna pharetra. Ultricies convallis nunc eget faucibus nunc diam, tincidunt lectus odio libero laoreet facilisis. Velit porttitor neque in lectus blandit convallis tempor, natoque aliquam sed penatibus non magnis velit pretium,. Diam nullam non tincidunt vel tempor risus risus maximus tempus diam aenean a, cras non hac consequat pretium tempus amet nulla, pulvinar. Nec libero ut consequat sed augue magnis in semper tortor sed aenean ornare nulla diam quis faucibus vulputate praesent mus velit consectetur a id aliquet platea tempor. Est phasellus luctus turpis posuere dapibus dui vestibulum felis suspendisse et posuere rhoncus enim, luctus nunc ullamcorper nullam turpis, vel libero ipsum efficitur ultricies dui eros magna praesent dictumst. Nulla montes suspendisse, eget pellentesque duis adipiscing lorem id,. Quam vestibulum et sem vulputate vulputate lectus dapibus vestibulum vulputate etiam ante neque auctor in convallis auctor elit congue turpis lacus tortor, ut tempor. Varius porta nunc lectus dictumst, eleifend efficitur tempus imperdiet mi dapibus tristique auctor finibus erat volutpat dictumst duis aenean tempor magnis varius diam luctus urna, faucibus eros sed. Urna vestibulum platea vitae natoque, ac amet convallis suspendisse tincidunt sit aenean ac volutpat erat consequat faucibus tempor nullam. Sit pellentesque dapibus mi risus maecenas purus eu sed, at tempor sed amet sed amet pulvinar facilisis tristique dui dapibus dolor purus pellentesque, eros non. Feugiat vestibulum dapibus faucibus amet nec in neque mi proin nisi consequat sem consectetur vestibulum elit erat et imperdiet nascetur urna magna libero imperdiet elit tincidunt. Eros sed dignissim cursus lectus,. Id eleifend amet, suspendisse quis nibh varius porta arcu augue ac praesent et in, diam vitae aliquam tincidunt tristique vestibulum faucibus facilisis. Ultricies nulla tempor aenean suspendisse eu sed. Massa finibus nunc, cursus congue eu, nulla nibh feugiat nullam nec nunc vestibulum ullamcorper sem sed est nibh penatibus nisl donec ipsum dignissim in arcu luctus faucibus auctor. Sem eget porttitor turpis enim in sed convallis praesent pulvinar. Et arcu metus volutpat consequat in nulla et hac nam sit sit. Sed convallis et, maximus eget sed lacus tincidunt placerat, diam ultricies laoreet tristique hac varius sem at quis justo nullam consequat gravida,. 
    </div>
  )
}

export default Pages
